name: CI

on:
  push: {}
  pull_request: {}

jobs:

  build:
    runs-on: ubuntu-latest
    # Available images and software within each one:
    # <https://github.com/actions/runner-images#available-images>

    strategy:
      matrix:
        compiler:
        - gcc
        - gcc-9
        - gcc-10
        - gcc-11
        - gcc-12
        - clang-12
        - clang-13
        - clang-14

    steps:
    - name: Install build-dependencies
      run: sudo apt-get install libpam-dev
      
    - uses: actions/checkout@v2
      
    - uses: actions/setup-python@v1

    - uses: BSFishy/meson-build@v1.0.3
      env:
        CC: ${{ matrix.compiler }}
      with:
        action: build
        options: --verbose

    - uses: BSFishy/meson-build@v1.0.3
      with:
        action: test
        options: --verbose
