name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc
          - gcc-9
          - clang
          - clang-9
    steps:
    - name: Install build-dependencies
      run: sudo apt-get install libpam-dev
      
    - uses: actions/checkout@v2
      
    - uses: actions/setup-python@v1

    - uses: BSFishy/meson-build@v1.0.1
      env:
        CC: ${{ matrix.compiler }}
      with:
        action: build
        options: --verbose

    - uses: BSFishy/meson-build@v1.0.1
      with:
        action: test
        options: --verbose
